-- Question 1: What is the total revenue generated by the business?

SELECT ROUND(SUM("Revenue")::numeric, 2) AS total_revenue
FROM customer;


-- Question 2: How many unique orders were placed?

SELECT COUNT(DISTINCT "InvoiceNo") AS total_orders
FROM customer;


-- Question 3: How many unique customers made purchases?

SELECT COUNT(DISTINCT "CustomerID") AS total_customers
FROM customer;


-- Question 4: What is the average order value?

SELECT ROUND(AVG(order_value)::numeric, 2) AS average_order_value
FROM (
    SELECT "InvoiceNo",
           SUM("Revenue") AS order_value
    FROM customer
    GROUP BY "InvoiceNo"
) t;


-- Question 5: Which are the top 10 products by revenue?

SELECT "Description",
       ROUND(SUM("Revenue")::numeric, 2) AS revenue
FROM customer
GROUP BY "Description"
ORDER BY revenue DESC
LIMIT 10;


-- Question 6: Which are the top 10 products by quantity sold?

SELECT "Description",
       SUM("Quantity") AS quantity_sold
FROM customer
GROUP BY "Description"
ORDER BY quantity_sold DESC
LIMIT 10;


-- Question 7: Who are the top 10 customers by revenue generated?

SELECT "CustomerID",
       ROUND(SUM("Revenue")::numeric, 2) AS revenue
FROM customer
GROUP BY "CustomerID"
ORDER BY revenue DESC
LIMIT 10;


-- Question 8: Which countries generate the highest revenue?

SELECT "Country",
       ROUND(SUM("Revenue")::numeric, 2) AS revenue
FROM customer
GROUP BY "Country"
ORDER BY revenue DESC;


-- Question 9: What are the monthly sales trends and revenue patterns?

SELECT "Month_Name",
       ROUND(SUM("Revenue")::numeric, 2) AS revenue
FROM customer
GROUP BY "Month_Name"
ORDER BY revenue DESC;


-- Question 10: Which day of the week generates the highest revenue?

SELECT "Day_Name",
       ROUND(SUM("Revenue")::numeric, 2) AS revenue
FROM customer
GROUP BY "Day_Name"
ORDER BY revenue DESC;


-- Question 11: During which hours of the day is revenue highest?

SELECT "Hour",
       ROUND(SUM("Revenue")::numeric, 2) AS revenue
FROM customer
GROUP BY "Hour"
ORDER BY revenue DESC;


-- Question 12: Which customers place the highest number of orders?

SELECT "CustomerID",
       COUNT(DISTINCT "InvoiceNo") AS total_orders
FROM customer
GROUP BY "CustomerID"
ORDER BY total_orders DESC
LIMIT 10;


-- Question 13: What is the customer lifetime value (CLV) of each customer?

SELECT "CustomerID",
       ROUND(SUM("Revenue")::numeric, 2) AS customer_lifetime_value
FROM customer
GROUP BY "CustomerID"
ORDER BY customer_lifetime_value DESC;


-- Question 14: Which products have the highest average selling price?

SELECT "Description",
       ROUND(AVG("UnitPrice")::numeric, 2) AS avg_price
FROM customer
GROUP BY "Description"
ORDER BY avg_price DESC
LIMIT 10;


-- Question 15: How many customers are there in each country?

SELECT "Country",
       COUNT(DISTINCT "CustomerID") AS total_customers
FROM customer
GROUP BY "Country"
ORDER BY total_customers DESC;